    version: '2'
    services:
      webserver:
        image: nginx:alpine
        volumes:
          - ./code:/var/www
                ## copy nginx configuration for our application ##
          - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
                ## run the webserver on port 8080 ##
          - "8080:80"
      app:
            ## read php image from our custom docker image ##
        build:
          context: .
          dockerfile: ./docker/php/Dockerfile
        volumes:
          ## copy project files to /var/www ##
          - ./code:/var/www
        working_dir: /var/www

      db:
        image: mysql:5.7
        ## expose the mysql port to our machine so we can access it from any mysql-client like TablePlus ##
        ports:
          - "3388:3306"
       ## keep mysql data on localhost so we don't lose them ##
        volumes:
          - ./docker-volumes-data/db:/var/lib/database
        environment:
          MYSQL_DATABASE: laravel_db
          MYSQL_ROOT_PASSWORD: root
      pma:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
          - 8081:80
        depends_on:
          - db
        environment:
          PMA_HOST: db
          MYSQL_ROOT_PASSWORD: root

      redis:
        image: redis
        volumes:
          ## keep redis data on localhost so we don't lose them ##
          - ./docker-volumes-data/redis:/data
